@extends('client.layouts.home')
@section('heroSlider')
@include('client.modules.home.contents.heroSlider')
@endsection
@section('smallBanner')
@include('client.modules.home.contents.smallBanner')
@endsection
@section('productArea')
@include('client.modules.home.contents.productArea')
@endsection
@section('midiumBanner')
@include('client.modules.home.contents.midiumBanner')
@endsection
@section('mostPopular')
@include('client.modules.home.contents.mostPopular')
@endsection
@section('shopHomeList')
@include('client.modules.home.contents.shopHomeList')
@endsection
@section('cownDown')
@include('client.modules.home.contents.cownDown')
@endsection
@section('shopBlog')
@include('client.modules.home.contents.shopBlog')
@endsection
@section('shopServices')
@include('client.modules.home.contents.shopServices')
@endsection
@section('shopNewsletter')
@include('client.modules.home.contents.shopNewsletter')
@endsection